title: Linbo Qing's Homepage
page-top-title: Linbo Qing
top-section-bg-text: Computer Science
home-subtitle: Linbo Qing&ensp;|&ensp;卿粼波
copyright-text: '&copy; Linbo Qing 2023-2024. All Rights Reserved.'
